columnSuffix: drdgouij
contentColumnType: text
fieldGroup: 1f179349-4990-4beb-95fd-ca4178d4a5dd # Event
handle: event_subtitle
instructions: ''
name: Sottotitolo
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
