defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  b1203dd8-886c-4fda-967b-fd30fc1fb44d: # tsm vicenza
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
